[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
eval = "0.4.3"
meval = "0.2.0"
rand = "0.8.5"
serde_json = "1.0.128"

[[bin]]
name = "cli"
path = "src/cli.rs"
